MODEL:
  META_ARCHITECTURE: "Detr"
  PIXEL_MEAN: [123.675, 116.280, 103.530]
  PIXEL_STD: [58.395, 57.120, 57.375]
  MASK_ON: False
  BACKBONE:
    NAME: "FBNetV2C4Backbone"
  FBNET_V2:
    ARCH: "FBNetV3_A_dsmask_C5"
    NORM: "sync_bn"
    WIDTH_DIVISOR: 8
    SCALE_FACTOR: 1.0
    OUT_FEATURES: ["trunk4"]
  DETR:
    NAME: "DETR"
    GIOU_WEIGHT: 2.0
    L1_WEIGHT: 5.0
    NUM_OBJECT_QUERIES: 100
DATASETS:
  TRAIN: ("coco_2017_train",)
  TEST: ("coco_2017_val",)
SOLVER:
  IMS_PER_BATCH: 16
  BASE_LR: 0.0001
  STEPS: (1478400,)
  MAX_ITER: 2217600
  WARMUP_FACTOR: 1.0
  WARMUP_ITERS: 10
  WEIGHT_DECAY: 0.0001
  OPTIMIZER: "ADAMW"
  CLIP_GRADIENTS:
    ENABLED: True
    CLIP_TYPE: "full_model"
    CLIP_VALUE: 0.1
    NORM_TYPE: 2.0
  LR_MULTIPLIER_OVERWRITE: [{'backbone': 0.1}]
INPUT:
  MIN_SIZE_TRAIN: (480, 512, 544, 576, 608, 640, 672, 704, 736, 768, 800)
  CROP:
    ENABLED: True
    TYPE: "absolute_range"
    SIZE: (384, 600)
  FORMAT: "RGB"
D2GO_DATA:
  MAPPER:
    NAME: "DETRDatasetMapper"
TEST:
  EVAL_PERIOD: 4000
DATALOADER:
  FILTER_EMPTY_ANNOTATIONS: False
  NUM_WORKERS: 4
VERSION: 2
